root@master1:~/jobs# cat cron-pod.yaml

apiVersion: batch/v1
kind: CronJob
metadata:
  name: working
spec:
  JobTemplate:
    metadata:
      name: working
    spec:
      containers:
      - name: working
        image: python
        args:
        - "/bin/sh"
        - "-c"
        - "ps –eaf"
      restartPolicy: OnFailure
